### ISSUE TITLE
Problem parsing incoming data from Metasploit

### ISSUE THREAD

**Issue by nrathaus** [msgpack/msgpack-perl#20]
The following hexdump of the data that comes in from Metasploit:
```
   00000000  82 C4 06 72 65 73 75 6C - 74 C4 07 73 75 63 63 65  ...result..succe
   00000010  73 73 C4 05 74 6F 6B 65 - 6E C4 20 54 45 4D 50 31  ss..token. TEMP1
   00000020  53 42 49 6B 6B 33 6F 77 - 6A 54 58 6E 66 39 50 55  SBIkk3owjTXnf9PU
   00000030  79 70 4D 36 65 31 57 51 - 56 56 6A                 ypM6e1WQVVj
```

Is not parseable by the module and returns this error:
```
   Data::MessagePack->unpack: parse error at metasploit_rpc.pl line 59.
```

I cannot find the problem in the above data set, not locate the bug inside PP.pm

I also saw that to use this as the data I send to the server:
```
   my @hash = ["auth.login", "user", "pass"];
   my $request = Data::MessagePack->pack(\@hash);
```

I would need to trim the first byte of the request:
```
   $request = substr($request, 1);
```

Or the server won't be able to parse the information

I think it is somehow related

I am running this on Ubuntu 15.04 LTS, perl 5.20.2

**Comment by syohex** [comment]
`msgpack-perl` does not support newer data type of `bin8`, `bin16`, `bin32`, `ext8`, `ext16`, `ext32` etc. Your data contains those types and Data::MessagePack failed parsing it.

**Comment by nrathaus** [comment]
Hi

I see

Any easy way to add that?

I tried just now to modify the pp.pm but its not taking

Do I need to recompile it every time? Or is there some way?

Thanks,
Noam Rathaus
CTO
Beyond Security

**Comment by syohex** [comment]
> Any easy way to add that?

I suppose it is not easy.

**Comment by nrathaus** [comment]
Can you guide me through the process of adding it to the Module?

I am willing to put the effort into resolving this if you can help me get
my modified code under PP.pm to work, rather than .. something else ..
which I am guessing is the compiled version


On Thu, Aug 27, 2015 at 7:03 PM, Syohei YOSHIDA <notifications@github.com>
wrote:

> Any easy way to add that?
>
> I suppose it is not easy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-135478899>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
@nrathaus Sorry very too late reply. I sent PR at #22. Could you check #22 changes ?

You can try this by

```
% git clone git@github.com:syohex/msgpack-perl.git
% git checkout origin/bin-format
# Install dependencies of Data::MessagePack
% perl Makefile.PL
% make
% make test
% make install
```

**Comment by nrathaus** [comment]
Hi,

No worries about the reply

What would this fix/resolve?

Does it fix the bug?


On Thu, Sep 24, 2015 at 10:00 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> @nrathaus <https://github.com/nrathaus> Sorry very too late reply. I sent
> PR at #22 <https://github.com/msgpack/msgpack-perl/pull/22>. Could you
> check #22 <https://github.com/msgpack/msgpack-perl/pull/22> changes ?
>
> You can try this by
>
> % git clone git@github.com:syohex/msgpack-perl.git
> % git checkout origin/bin-format
> # Install dependencies of Data::MessagePack
> % perl Makefile.PL
> % make
> % make test
> % make install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-142834698>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
> What would this fix/resolve? Does it fix the bug?

It supports 'bin' format. Your data uses `bin` format. So I suppose it resolves your issue.

**Comment by nrathaus** [comment]
Hi,

I will give it a try, appreciate the effort


On Fri, Sep 25, 2015 at 8:58 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> What would this fix/resolve? Does it fix the bug?
>
> It supports 'bin' format. Your data uses bin format. So I suppose it
> resolves your issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143136507>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

Sorry for my lack of knowledge :) but when I try:
git clone git@github.com:syohex/msgpack-perl.git

I get:
loning into 'msgpack-perl'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129'
to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



On Fri, Sep 25, 2015 at 9:01 AM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> I will give it a try, appreciate the effort
>
>
> On Fri, Sep 25, 2015 at 8:58 AM, Syohei YOSHIDA <notifications@github.com>
> wrote:
>
>> What would this fix/resolve? Does it fix the bug?
>>
>> It supports 'bin' format. Your data uses bin format. So I suppose it
>> resolves your issue.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143136507>
>> .
>>
>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

I used this:
https://github.com/syohex/msgpack-perl.git

Instead, is that still including your patch?


On Mon, Sep 28, 2015 at 9:21 AM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> Sorry for my lack of knowledge :) but when I try:
> git clone git@github.com:syohex/msgpack-perl.git
>
> I get:
> loning into 'msgpack-perl'...
> Warning: Permanently added the RSA host key for IP address
> '192.30.252.129' to the list of known hosts.
> Permission denied (publickey).
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.
>
>
>
> On Fri, Sep 25, 2015 at 9:01 AM, Noam Rathaus <noamr@beyondsecurity.com>
> wrote:
>
>> Hi,
>>
>> I will give it a try, appreciate the effort
>>
>>
>> On Fri, Sep 25, 2015 at 8:58 AM, Syohei YOSHIDA <notifications@github.com
>> > wrote:
>>
>>> What would this fix/resolve? Does it fix the bug?
>>>
>>> It supports 'bin' format. Your data uses bin format. So I suppose it
>>> resolves your issue.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143136507>
>>> .
>>>
>>
>>
>>
>> --
>>
>> Thanks,
>> Noam Rathaus
>> Beyond Security
>>
>> PGP Key ID: 571934A6
>>
>>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
> I used this: https://github.com/syohex/msgpack-perl.git

Oh, sorry Please use https scheme, not git.

> Instead, is that still including your patch?

Yes, please use `bin-format`(`origin/bin-format`) branch

**Comment by nrathaus** [comment]
Hi,

It took me awhile to get the lab setup available, I am faced though with
something unexpected:
/usr/bin/perl: symbol lookup error:
/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
undefined symbol: msgpack_pack_raw

Looking around I cannot find (even inside Git) what provides this function,
I can't see it inside msgpack-c

So I must be looking at this error incorrectly



On Mon, Sep 28, 2015 at 9:25 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> I used this: https://github.com/syohex/msgpack-perl.git
>
> Oh, sorry Please use https scheme, not git.
>
> Instead, is that still including your patch?
>
> Yes, please use bin-format(origin/bin-format) branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143651116>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

1. I changed the code here:
xs-src/pack.c

To say:
msgpack_pack_v4raw
msgpack_pack_v4raw_body

And it now doesn't complain about symbolic links

2. The data return is now properly handled, thanks



On Thu, Oct 1, 2015 at 1:02 PM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> It took me awhile to get the lab setup available, I am faced though with
> something unexpected:
> /usr/bin/perl: symbol lookup error:
> /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
> undefined symbol: msgpack_pack_raw
>
> Looking around I cannot find (even inside Git) what provides this
> function, I can't see it inside msgpack-c
>
> So I must be looking at this error incorrectly
>
>
>
> On Mon, Sep 28, 2015 at 9:25 AM, Syohei YOSHIDA <notifications@github.com>
> wrote:
>
>> I used this: https://github.com/syohex/msgpack-perl.git
>>
>> Oh, sorry Please use https scheme, not git.
>>
>> Instead, is that still including your patch?
>>
>> Yes, please use bin-format(origin/bin-format) branch
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143651116>
>> .
>>
>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

A few more lines of code "down" and I get another undefined symbol, so I
believe something isn't properly compiled
/usr/bin/perl: symbol lookup error:
/usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
undefined symbol: template_callback_str



On Thu, Oct 1, 2015 at 1:31 PM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> 1. I changed the code here:
> xs-src/pack.c
>
> To say:
> msgpack_pack_v4raw
> msgpack_pack_v4raw_body
>
> And it now doesn't complain about symbolic links
>
> 2. The data return is now properly handled, thanks
>
>
>
> On Thu, Oct 1, 2015 at 1:02 PM, Noam Rathaus <noamr@beyondsecurity.com>
> wrote:
>
>> Hi,
>>
>> It took me awhile to get the lab setup available, I am faced though with
>> something unexpected:
>> /usr/bin/perl: symbol lookup error:
>> /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
>> undefined symbol: msgpack_pack_raw
>>
>> Looking around I cannot find (even inside Git) what provides this
>> function, I can't see it inside msgpack-c
>>
>> So I must be looking at this error incorrectly
>>
>>
>>
>> On Mon, Sep 28, 2015 at 9:25 AM, Syohei YOSHIDA <notifications@github.com
>> > wrote:
>>
>>> I used this: https://github.com/syohex/msgpack-perl.git
>>>
>>> Oh, sorry Please use https scheme, not git.
>>>
>>> Instead, is that still including your patch?
>>>
>>> Yes, please use bin-format(origin/bin-format) branch
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143651116>
>>> .
>>>
>>
>>
>>
>> --
>>
>> Thanks,
>> Noam Rathaus
>> Beyond Security
>>
>> PGP Key ID: 571934A6
>>
>>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
Thanks for report. I updated 
- https://github.com/syohex/msgpack-perl/commit/0e712cb7f4514e6da185fd2a5efa47884296fd23
- https://github.com/syohex/msgpack-perl/commit/1ffdc6bcee1bbdb20b4ce2e9152b94abd074c855

Please upgrade latest version.

**Comment by nrathaus** [comment]
Hi,

You can recreate it by trying to unpack:
00000000  83 C4 07 76 65 72 73 69 - 6F 6E B3 34 2E 31 31 2E
 ...version.4.11.
00000010  34 2D 64 65 76 2D 39 32 - 37 37 38 35 63 66 C4 04
 4-dev-927785cf..
00000020  72 75 62 79 D9 21 32 2E - 31 2E 32 20 78 38 36 5F  ruby.!2.1.2
x86_
00000030  36 34 2D 6C 69 6E 75 78 - 2D 67 6E 75 20 32 30 31  64-linux-gnu
201
00000040  34 2D 30 35 2D 30 38 C4 - 03 61 70 69 C4 03 31 2E
 4-05-08..api..1.
00000050  30                                                 0


On Thu, Oct 1, 2015 at 1:39 PM, Noam Rathaus <noamr@beyondsecurity.com>
wrote:

> Hi,
>
> A few more lines of code "down" and I get another undefined symbol, so I
> believe something isn't properly compiled
> /usr/bin/perl: symbol lookup error:
> /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
> undefined symbol: template_callback_str
>
>
>
> On Thu, Oct 1, 2015 at 1:31 PM, Noam Rathaus <noamr@beyondsecurity.com>
> wrote:
>
>> Hi,
>>
>> 1. I changed the code here:
>> xs-src/pack.c
>>
>> To say:
>> msgpack_pack_v4raw
>> msgpack_pack_v4raw_body
>>
>> And it now doesn't complain about symbolic links
>>
>> 2. The data return is now properly handled, thanks
>>
>>
>>
>> On Thu, Oct 1, 2015 at 1:02 PM, Noam Rathaus <noamr@beyondsecurity.com>
>> wrote:
>>
>>> Hi,
>>>
>>> It took me awhile to get the lab setup available, I am faced though with
>>> something unexpected:
>>> /usr/bin/perl: symbol lookup error:
>>> /usr/local/lib/x86_64-linux-gnu/perl/5.20.2/auto/Data/MessagePack/MessagePack.so:
>>> undefined symbol: msgpack_pack_raw
>>>
>>> Looking around I cannot find (even inside Git) what provides this
>>> function, I can't see it inside msgpack-c
>>>
>>> So I must be looking at this error incorrectly
>>>
>>>
>>>
>>> On Mon, Sep 28, 2015 at 9:25 AM, Syohei YOSHIDA <
>>> notifications@github.com> wrote:
>>>
>>>> I used this: https://github.com/syohex/msgpack-perl.git
>>>>
>>>> Oh, sorry Please use https scheme, not git.
>>>>
>>>> Instead, is that still including your patch?
>>>>
>>>> Yes, please use bin-format(origin/bin-format) branch
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-143651116>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>>
>>> Thanks,
>>> Noam Rathaus
>>> Beyond Security
>>>
>>> PGP Key ID: 571934A6
>>>
>>>
>>
>>
>> --
>>
>> Thanks,
>> Noam Rathaus
>> Beyond Security
>>
>> PGP Key ID: 571934A6
>>
>>
>
>
> --
>
> Thanks,
> Noam Rathaus
> Beyond Security
>
> PGP Key ID: 571934A6
>
>


-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by nrathaus** [comment]
Hi,

No bugs at the moment, this change fixed both issues


On Thu, Oct 1, 2015 at 1:41 PM, Syohei YOSHIDA <notifications@github.com>
wrote:

> Thanks for report. I updated
>
>    - syohex@0e712cb
>    <https://github.com/syohex/msgpack-perl/commit/0e712cb7f4514e6da185fd2a5efa47884296fd23>
>    - syohex@1ffdc6b
>    <https://github.com/syohex/msgpack-perl/commit/1ffdc6bcee1bbdb20b4ce2e9152b94abd074c855>
>
> Please upgrade latest version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-144690871>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
I have merged bin/str support into master branch. Sorry very too late response.

**Comment by nrathaus** [comment]
Hi,

No problem


On Mon, Feb 29, 2016 at 7:30 AM, Syohei YOSHIDA <notifications@github.com>
wrote:

> I have merged bin/str support into master branch. Sorry very too late
> response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msgpack/msgpack-perl/issues/20#issuecomment-190051644>
> .
>



-- 

Thanks,
Noam Rathaus
Beyond Security

PGP Key ID: 571934A6

**Comment by syohex** [comment]
I have released trial version https://metacpan.org/release/SYOHEX/Data-MessagePack-0.49_01.

Thanks for reporting issue. Please report us if you have any problems.
